apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          serviceAccountName: vault-backup
          containers:
            - name: backup
              image: hashicorp/vault:1.19.0
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  export VAULT_ADDR=http://vault-active.vault.svc:8200

                  echo "Authenticating with Vault using Kubernetes auth..."
                  export VAULT_TOKEN=$(vault write -field=token auth/kubernetes/login \
                    role=vault-backup \
                    jwt=@/var/run/secrets/kubernetes.io/serviceaccount/token)

                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  BACKUP_FILE="/backup/vault-snapshot-${TIMESTAMP}.snap"

                  echo "Starting Vault backup..."
                  vault operator raft snapshot save "$BACKUP_FILE"

                  # Keep only last 7 daily backups
                  echo "Cleaning up old backups..."
                  find /backup -name "vault-snapshot-*.snap" -mtime +7 -delete || echo "Warning: cleanup failed, continuing..."

                  echo "Backup completed: $BACKUP_FILE"
                  ls -lah /backup/ || echo "Warning: could not list backup directory"
              volumeMounts:
                - name: backup-volume
                  mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-volume
              nfs:
                server: 192.168.1.10
                path: /mnt/user/backup/vault
