apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: vault
  namespace: vault
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "vault.talos.froystein.jp"
  rules:
    - backendRefs:
        - name: vault-ui
          port: 8200
