apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: default
  namespace: vault
spec:
  namespace: ""
  method: kubernetes
  mount: kubernetes
  allowedNamespaces:
    - "*"
  kubernetes:
    role: vault-secrets-operator
    serviceAccount: default
    audiences:
      - vault
