apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vllm-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: vllm-stack
    repoURL: https://vllm-project.github.io/production-stack
    targetRevision: 0.1.8
    helm:
      values: |
        routerSpec:
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
            limits:
              memory: 1Gi

        servingEngineSpec:
          runtimeClassName: ""
          modelSpec:
          - name: "gemma2"
            repository: "public.ecr.aws/q9t5s3a7/vllm-cpu-release-repo"
            tag: "v0.7.2"
            modelURL: "google/gemma-2-2b-it"

            replicaCount: 1

            requestCPU: 6
            requestMemory: "16Gi"

            pvcStorage: "50Gi"
            pvcAccessMode:
              - ReadWriteMany

            hf_token:
              secretName: "vllm-hf-token"
              secretKey: "token"

            vllmConfig:
              dtype: "bfloat16"
              extraArgs:
                - "--device"
                - "cpu"

            env:
              - name: VLLM_CPU_KVCACHE_SPACE
                value: "8"

  destination:
    server: https://kubernetes.default.svc
    namespace: vllm
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
