apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gemma2-epp
  namespace: vllm
rules:
  - apiGroups:
      - inference.networking.k8s.io
    resources:
      - inferencepools
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gemma2-epp
  namespace: vllm
subjects:
  - kind: ServiceAccount
    name: gemma2-epp
    namespace: vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gemma2-epp
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gemma2-epp-auth-reviewer
rules:
  - apiGroups:
      - authentication.k8s.io
    resources:
      - tokenreviews
    verbs:
      - create
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gemma2-epp-auth-reviewer
subjects:
  - kind: ServiceAccount
    name: gemma2-epp
    namespace: vllm
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gemma2-epp-auth-reviewer
