apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm
  namespace: vllm
  labels:
    app.kubernetes.io/name: vllm
spec:
  selector:
    matchLabels:
      helm-release-name: vllm-chart
  podMetricsEndpoints:
    - port: container-port
      interval: 30s
      path: /metrics
