apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: metallb-system
spec:
  ipAddressPools:
    - default
  interfaces:
    - enp1s0
---
kind: IPAddressPool
apiVersion: metallb.io/v1beta1
metadata:
  name: default
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.20-192.168.1.99
