apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: cilium
    repoURL: https://helm.cilium.io
    targetRevision: 1.18.3
    helm:
      releaseName: cilium
      parameters:
        - name: ipam.mode
          value: "kubernetes"
        - name: kubeProxyReplacement
          value: "true"
        - name: securityContext.privileged
          value: "true"
        - name: securityContext.capabilities.cilumAgent
          value: "{CHOWN,KILL,NET_ADMIN,NET_RAW,IPC_LOCK,SYS_ADMIN,SYS_RESOURCE,DAC_OVERRIDE,FOWNER,SETGID,SETUID}"
        - name: securityContext.capabilities.cleanCiliumState
          value: "{NET_ADMIN,SYS_ADMIN,SYS_RESOURCE}"
        - name: cgroup.autoMount.enabled
          value: "false"
        - name: cgroup.hostRoot
          value: "/sys/fs/cgroup"
        - name: k8sServiceHost
          value: "localhost"
        - name: k8sServicePort
          value: "7445"
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
