apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kemuri
  namespace: kemuri
  labels:
    app.kubernetes.io/name: kemuri
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kemuri
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 5s
