apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kubevirt-manager
  namespace: kube-system
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "kubevirt-manager.talos.froystein.jp"
  rules:
    - backendRefs:
        - name: kubevirt-manager
          port: 8080
