apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: headlamp-oidc
  namespace: headlamp
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: headlamp/oidc
  refreshAfter: 60s
  destination:
    name: headlamp-oidc
    create: true
