apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 79.4.1
    helm:
      releaseName: kube-prom-stack
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi

        grafana:
          persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            accessModes:
              - ReadWriteMany
            size: 10Gi
            finalizers:
              - kubernetes.io/pvc-protection

          envValueFrom:
            GF_AUTH_GITHUB_CLIENT_ID:
              secretKeyRef:
                name: grafana-github-oauth
                key: client-id
            GF_AUTH_GITHUB_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-github-oauth
                key: client-secret

          grafana.ini:
            server:
              protocol: http
              root_url: https://grafana.talos.froystein.jp
            auth.github:
              enabled: true
              client_id: $GF_AUTH_GITHUB_CLIENT_ID
              client_secret: $GF_AUTH_GITHUB_CLIENT_SECRET
              scopes: user:email,read:org
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              allow_sign_up: true
              auto_login: true
              role_attribute_path: "[login=='stianfro'][0] && 'GrafanaAdmin' || 'Viewer'"
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: false
      selfHeal: false
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      name: kube-prom-stack-grafana
      jsonPointers:
        - /data
