apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 79.4.1
    helm:
      releaseName: kube-prom-stack
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi

        grafana:
          persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            accessModes:
              - ReadWriteMany
            size: 10Gi
            finalizers:
              - kubernetes.io/pvc-protection

          grafana.ini:
            server:
              protocol: http
              root_url: https://grafana.talos.froystein.jp
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
