apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  source:
    chart: kube-prometheus-stack
    repoURL: ghcr.io/prometheus-community/charts
    targetRevision: 79.4.1
    helm:
      releaseName: kube-prom-stack
      values: |
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            enableFeatures:
              - exemplar-storage
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: longhorn
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: 50Gi
            additionalScrapeConfigs:
              - job_name: 'etcd'
                static_configs:
                  - targets:
                      - 192.168.1.100:2381
                      - 192.168.1.101:2381
                      - 192.168.1.102:2381
                    labels:
                      job: etcd
                relabel_configs:
                  - source_labels: [__address__]
                    regex: '([^:]+):\d+'
                    target_label: instance
                    replacement: '$1'
                  - source_labels: [__address__]
                    regex: '192\.168\.1\.100:.*'
                    target_label: node
                    replacement: 'talos-0'
                  - source_labels: [__address__]
                    regex: '192\.168\.1\.101:.*'
                    target_label: node
                    replacement: 'talos-1'
                  - source_labels: [__address__]
                    regex: '192\.168\.1\.102:.*'
                    target_label: node
                    replacement: 'talos-2'

              - job_name: 'nasse'
                static_configs:
                  - targets:
                      - 192.168.1.10:9100
                    labels:
                      job: node-exporter
                relabel_configs:
                  - source_labels: [__address__]
                    regex: '([^:]+):\d+'
                    target_label: instance
                    replacement: '$1'


        grafana:
          persistence:
            enabled: true
            type: pvc
            storageClassName: longhorn
            accessModes:
              - ReadWriteMany
            size: 10Gi
            finalizers:
              - kubernetes.io/pvc-protection

          envValueFrom:
            GF_AUTH_GITHUB_CLIENT_ID:
              secretKeyRef:
                name: grafana-github-oauth
                key: client-id
            GF_AUTH_GITHUB_CLIENT_SECRET:
              secretKeyRef:
                name: grafana-github-oauth
                key: client-secret

          grafana.ini:
            server:
              protocol: http
              root_url: https://grafana.talos.froystein.jp
            auth.github:
              enabled: true
              scopes: user:email,read:org
              auth_url: https://github.com/login/oauth/authorize
              token_url: https://github.com/login/oauth/access_token
              api_url: https://api.github.com/user
              allow_sign_up: true
              auto_login: true
              role_attribute_path: "[login=='stianfro'][0] && 'GrafanaAdmin' || 'Viewer'"

          additionalDataSources:
            - name: Loki
              type: loki
              access: proxy
              url: http://loki-gateway.loki.svc.cluster.local
              isDefault: false
              editable: false
              orgId: 1
              version: 1
              jsonData:
                maxLines: 1000
                derivedFields:
                  - datasourceUid: tempo
                    matcherRegex: "traceID=(\\w+)"
                    name: TraceID
                    url: "$${__value.raw}"

            - name: Tempo
              uid: tempo
              type: tempo
              access: proxy
              url: http://tempo.tempo.svc.cluster.local:3100
              isDefault: false
              editable: false
              orgId: 1
              version: 1
              jsonData:
                tracesToLogsV2:
                  datasourceUid: loki
                  spanStartTimeShift: '-1h'
                  spanEndTimeShift: '1h'
                  filterByTraceID: true
                  filterBySpanID: false
                  customQuery: false
                  tags:
                    - key: 'service.name'
                      value: 'service_name'
                tracesToMetrics:
                  datasourceUid: prometheus
                  spanStartTimeShift: '-1h'
                  spanEndTimeShift: '1h'
                  tags:
                    - key: 'service.name'
                      value: 'service'
                  queries:
                    - name: 'Request Rate'
                      query: 'rate(traces_spanmetrics_calls_total{$$__tags}[5m])'
                serviceMap:
                  datasourceUid: prometheus
                nodeGraph:
                  enabled: true
                search:
                  hide: false
                lokiSearch:
                  datasourceUid: loki
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
  ignoreDifferences:
    - kind: Secret
      name: kube-prom-stack-grafana
      jsonPointers:
        - /data
