---
apiVersion: v1
kind: Service
metadata:
  name: etcd-metrics
  namespace: kube-system
  labels:
    app: etcd
    component: etcd
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 2381
      targetPort: 2381
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: etcd-metrics
  namespace: kube-system
  labels:
    app: etcd
    component: etcd
subsets:
  - addresses:
      - ip: 192.168.1.100
        nodeName: talos-0
      - ip: 192.168.1.101
        nodeName: talos-1
      - ip: 192.168.1.102
        nodeName: talos-2
    ports:
      - name: metrics
        port: 2381
        protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: etcd-metrics
  namespace: kube-system
  labels:
    app: etcd
    component: etcd
spec:
  endpoints:
    - port: metrics
      interval: 30s
      scheme: http
      relabelings:
        - sourceLabels: [__address__]
          targetLabel: instance
        - targetLabel: job
          replacement: etcd
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: etcd
      component: etcd
