apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
  name: lab
spec:
  bgpInstances:
    - name: instance-64512
      localASN: 64512
      peers:
        - name: frr-router
          peerASN: 64513
          peerAddress: 192.168.1.159
          peerConfigRef:
            name: frr-router
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
  name: frr-router
spec:
  timers:
    holdTimeSeconds: 9
    keepAliveTimeSeconds: 3
  gracefulRestart:
    enabled: true
    restartTimeSeconds: 15
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: bgp-services
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
  name: bgp-services
  labels:
    advertise: bgp-services
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          lb-pool: bgp
