apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: blog-git-credentials
  namespace: blog
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: blog/git-credentials
  refreshAfter: 60s
  destination:
    name: blog-git-credentials
    create: true
    labels:
      kargo.akuity.io/cred-type: git
    annotations:
      kargo.akuity.io/cred-type: git
