apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: iso-url
  namespace: ocp-upgrade-lab
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: iso
  refreshAfter: 3600s
  destination:
    name: iso-url
    create: true
