apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-umami
  namespace: authentik
data:
  umami.yaml: |
    version: 1
    metadata:
      name: Umami analytics
      labels:
        blueprints.goauthentik.io/instantiate: "true"
    entries:
      - id: umami-provider
        model: authentik_providers_proxy.proxyprovider
        identifiers:
          name: Umami analytics
        attrs:
          authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-provider-invalidation-flow]]
          external_host: https://analytics.talos.froystein.jp
          mode: forward_single
      - id: umami-application
        model: authentik_core.application
        identifiers:
          slug: umami
        attrs:
          name: Umami analytics
          provider: !KeyOf umami-provider
          meta_launch_url: https://analytics.talos.froystein.jp
      - model: authentik_outposts.outpost
        identifiers:
          name: authentik Embedded Outpost
        attrs:
          providers:
            - !KeyOf umami-provider
