apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-chart
  namespace: argocd
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.10.0
      helm:
        values: |
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            backupTarget: nfs://192.168.1.10:/mnt/user/backup/longhorn
            backupTargetCredentialSecret: ""
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
