apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "longhown.talos.froystein.jp"
  rules:
    - backendRefs:
        - name: longhorn-frontend
          port: 80
