apiVersion: apps/v1
kind: Deployment
metadata:
  name: froystein-jp
  namespace: froystein-jp
spec:
  template:
    spec:
      containers:
        - name: web
          volumeMounts:
            - name: analytics-config
              mountPath: /usr/share/nginx/html/analytics-config.js
              subPath: analytics-config.js
              readOnly: true
      volumes:
        - name: analytics-config
          configMap:
            name: froystein-jp-analytics-config
