apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/stianfro/froystein.jp/6affc3596216731f4934abe051100ff0c6fd0477/manifests.yaml
  - analytics-route.yaml
configMapGenerator:
  - name: froystein-jp-analytics-config
    namespace: froystein-jp
    files:
      - analytics-config.js
patches:
  - path: deployment-patch.yaml
