apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kargo-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: kargo
    repoURL: ghcr.io/akuity/kargo-charts
    targetRevision: 1.8.4
    helm:
      values: |
        api:
          tls:
            enabled: false
          argocd:
            urls:
              - https://argo.talos.froystein.jp
          oidc:
            enabled: true
            issuerURL: https://authentik.talos.froystein.jp/application/o/kargo/
            clientID: 1FVXxMNpaJwAmtUvEB1277tJFUp6AsfnBrV0h776
            cliClientID: 1FVXxMNpaJwAmtUvEB1277tJFUp6AsfnBrV0h776
            dex:
              enabled: false
            admins:
              claims:
                groups:
                  - argo-admin
          adminAccount:
            enabled: false
        controller:
          argocd:
            integrationEnabled: true
            namespace: argocd
          rollouts:
            integrationEnabled: true
  destination:
    namespace: kargo
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
