apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kargo
  namespace: kargo
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "kargo.talos.froystein.jp"
  rules:
    - backendRefs:
        - name: kargo-api
          port: 80
