apiVersion: apps/v1
kind: Deployment
metadata:
  name: tabiji
  namespace: tabiji
  labels:
    app.kubernetes.io/name: tabiji
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: tabiji
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tabiji
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: web
          image: ghcr.io/stianfro/tabiji:sha-6101a2d@sha256:df15ef27e37586a7c21aee446242bf5040fc09ac8c15d7192f275c98d4805205
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 15
            failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
