apiVersion: v1
kind: Secret
metadata:
  name: kpack-builder-push
  namespace: kpack
  annotations:
    kpack.io/docker: registry.talos.froystein.jp
type: kubernetes.io/basic-auth
stringData:
  username: lab
  password: lab
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpack-builder
  namespace: kpack
  labels:
    app.kubernetes.io/part-of: minato
    minato.intility.com/component: build
secrets:
  - name: kpack-builder-push
imagePullSecrets:
  - name: kpack-builder-push
