apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: documents
  namespace: fc-accountant
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
