apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-collector-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: opentelemetry-collector
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.139.1
    helm:
      releaseName: otel-collector
      values: |
        mode: deployment

        extraEnvs:
          - name: LOGFIRE_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: logfire-credentials
                key: LOGFIRE_ENDPOINT
          - name: LOGFIRE_TOKEN
            valueFrom:
              secretKeyRef:
                name: logfire-credentials
                key: LOGFIRE_TOKEN

        image:
          repository: otel/opentelemetry-collector-contrib
          tag: 0.139.0

        presets:
          kubernetesAttributes:
            enabled: false  # Disabled - interferes with k8seventsreceiver resource attributes
          kubeletMetrics:
            enabled: false

        config:
          receivers:
            k8s_events:
              # Watch all namespaces for VirtualMachineInstance events
              auth_type: serviceAccount
              namespaces: []  # Empty array = watch all namespaces

            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318

          processors:
            # Filter to only VirtualMachineInstance and VirtualMachineInstanceMigration events
            # Note: Filter DROPS events that match the condition, so we use NOT to invert
            filter/kubevirt:
              logs:
                log_record:
                  - 'not IsMatch(resource.attributes["k8s.object.kind"], "^VirtualMachineInstance")'

            batch:
              timeout: 10s
              send_batch_size: 1024

            # Add resource attributes for better filtering
            resource:
              attributes:
                - key: service.name
                  value: kubevirt-events
                  action: insert

          exporters:
            debug:
              verbosity: detailed

            otlphttp:
              endpoint: http://loki-gateway.loki.svc.cluster.local/otlp
              tls:
                insecure: true

            otlphttp/logfire:
              endpoint: ${env:LOGFIRE_ENDPOINT}
              headers:
                Authorization: ${env:LOGFIRE_TOKEN}

          service:
            pipelines:
              logs:
                receivers: [k8s_events]
                processors: [filter/kubevirt, resource, batch]
                exporters: [debug, otlphttp]

              traces:
                receivers: [otlp]
                processors: [batch]
                exporters: [debug, otlphttp/logfire]

        # RBAC for reading events cluster-wide
        clusterRole:
          create: true
          rules:
            - apiGroups: [""]
              resources: ["events"]
              verbs: ["get", "list", "watch"]
            - apiGroups: [""]
              resources: ["namespaces", "pods"]
              verbs: ["get", "list", "watch"]

        service:
          enabled: true
          type: ClusterIP

        ports:
          otlp:
            enabled: true
            containerPort: 4317
            servicePort: 4317
            hostPort: 4317
            protocol: TCP
          otlp-http:
            enabled: true
            containerPort: 4318
            servicePort: 4318
            hostPort: 4318
            protocol: TCP

        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi

  destination:
    namespace: otel-collector
    server: https://kubernetes.default.svc

  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
