apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-tunnel-credentials
  namespace: cloudflare-tunnel
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: cloudflare-tunnel/credentials
  refreshAfter: 1h
  destination:
    name: cloudflare-tunnel-credentials
    create: true
    labels:
      app.kubernetes.io/name: cloudflare-tunnel
    transformation:
      excludeRaw: true
      templates:
        credentials.json:
          text: |
            {
              "AccountTag": "{{ .Secrets.account_id }}",
              "TunnelSecret": "{{ .Secrets.tunnel_secret }}",
              "TunnelID": "{{ .Secrets.tunnel_id }}"
            }
