apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - storageclass-local.yaml
  - namespace.yaml
  - vm.yaml
  - service.yaml
  - node-exporter-service.yaml
  - servicemonitor.yaml
configMapGenerator:
  - name: devbox-grafana-dashboards
    namespace: devbox
    files:
      - dashboards/agent-usage.json
    options:
      labels:
        grafana_dashboard: "1"
