apiVersion: v1
kind: Service
metadata:
  name: devbox-node-exporter
  namespace: devbox
  labels:
    app.kubernetes.io/name: devbox-node-exporter
    app.kubernetes.io/part-of: devbox
spec:
  type: ClusterIP
  selector:
    vm.kubevirt.io/name: devbox
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
      protocol: TCP
