apiVersion: v1
kind: Service
metadata:
  name: devbox-ssh
  namespace: devbox
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.51
spec:
  type: LoadBalancer
  selector:
    vm.kubevirt.io/name: devbox
  ports:
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: opencode-web
      port: 4096
      targetPort: 4096
      protocol: TCP
