apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devbox-node-exporter
  namespace: devbox
  labels:
    app.kubernetes.io/name: devbox-node-exporter
    app.kubernetes.io/part-of: devbox
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: devbox-node-exporter
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
