apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  namespace: mosquitto
  labels:
    app.kubernetes.io/name: mosquitto
  annotations:
    metallb.io/loadBalancerIPs: 192.168.1.21
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: mosquitto
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
      protocol: TCP
