apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: mosquitto-credentials
  namespace: mosquitto
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: office-call/mqtt
  refreshAfter: 1h
  destination:
    name: mosquitto-credentials
    create: true
    transformation:
      excludeRaw: true
      templates:
        homeassistant_password:
          text: '{{ .Secrets.homeassistant_password }}'
        pizero_password:
          text: '{{ .Secrets.pizero_password }}'
        exporter_password:
          text: '{{ .Secrets.exporter_password }}'
