apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dex
  namespace: dex
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - "dex.talos.froystein.jp"
  rules:
    - backendRefs:
        - name: dex
          port: 5556
