apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dex-secrets
  namespace: dex
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: dex/secrets
  refreshAfter: 60s
  destination:
    name: dex-secrets
    create: true
