apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: dex-config
  namespace: dex
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: dex/config
  refreshAfter: 60s
  destination:
    name: dex-config
    create: true
