apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - httproute.yaml
  - monitoring.yaml

configMapGenerator:
  - name: home-assistant-grafana-dashboards
    namespace: home-assistant
    files:
      - dashboards/office-call.json
    options:
      labels:
        grafana_dashboard: "1"

generatorOptions:
  disableNameSuffixHash: true
