apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - datavolume.yaml
  - vaultstaticsecrets.yaml
  - vm.yaml
  - service.yaml
  - gateway-firewall-configmap.yaml
  - gateway.yaml
  - networkpolicy.yaml
