#!/usr/bin/env bash
set -euo pipefail

target="${1:-${DEVBOX_SSH_TARGET:-devbox}}"
dry_run="${DEVBOX_SYNC_DRY_RUN:-0}"
tmpdir="$(mktemp -d)"

cleanup() {
  rm -rf "$tmpdir"
}
trap cleanup EXIT

rsync_flags=(-az)
if [[ "$dry_run" == "1" ]]; then
  rsync_flags+=(-n -v)
fi

log() {
  printf 'devbox-sync: %s\n' "$*"
}

remote_mkdir() {
  ssh "$target" "mkdir -p $*"
}

rsync_if_exists() {
  local src="$1"
  local dest="$2"
  shift 2
  if [[ -e "$src" ]]; then
    rsync "${rsync_flags[@]}" "$@" "$src" "$dest"
  fi
}

generate_codex_config() {
  local src="$HOME/.codex/config.toml"
  local dest="$tmpdir/codex-config.toml"

  if [[ ! -f "$src" ]]; then
    return 0
  fi

  python3 - "$src" "$dest" <<'PY'
from pathlib import Path
import sys
import tomllib

src = Path(sys.argv[1])
dest = Path(sys.argv[2])
cfg = tomllib.loads(src.read_text())

top_level_keys = [
    "model",
    "instructions",
    "model_reasoning_effort",
    "plan_mode_reasoning_effort",
    "service_tier",
    "personality",
]

def write_string(key, value):
    if "\n" in value:
        safe = value.replace('"""', '\\"\\"\\"')
        return f'{key} = """\n{safe}\n"""\n'
    return f'{key} = {value!r}\n'.replace("'", '"')

lines = [
    "# Generated by scripts/devbox-sync-personal-config.sh.",
    "# Personal values come from the workstation and are not stored in Git.",
    "",
]

for key in top_level_keys:
    value = cfg.get(key)
    if isinstance(value, str):
        lines.append(write_string(key, value).rstrip())
    elif isinstance(value, bool):
        lines.append(f"{key} = {str(value).lower()}")

features = cfg.get("features", {})
if isinstance(features, dict) and features.get("memories") is True:
    lines.extend(["", "[features]", "memories = true"])

dest.write_text("\n".join(lines).rstrip() + "\n")
PY

  rsync "${rsync_flags[@]}" "$dest" "$target:~/.codex/config.toml"
}

generate_claude_settings() {
  local src="$HOME/.claude/settings.json"
  local dest="$tmpdir/claude-settings.json"

  if [[ ! -f "$src" ]]; then
    return 0
  fi

  python3 - "$src" "$dest" <<'PY'
from pathlib import Path
import json
import sys

src = Path(sys.argv[1])
dest = Path(sys.argv[2])
cfg = json.loads(src.read_text())

safe_keys = [
    "env",
    "permissions",
    "model",
    "alwaysThinkingEnabled",
    "effortLevel",
    "showClearContextOnPlanAccept",
    "tui",
    "voice",
    "skipDangerousModePermissionPrompt",
    "theme",
    "editorMode",
    "preferredNotifChannel",
    "autoCompactEnabled",
    "teammateMode",
    "skipAutoPermissionPrompt",
    "voiceEnabled",
]

filtered = {
    key: cfg[key]
    for key in safe_keys
    if key in cfg
}

dest.write_text(json.dumps(filtered, indent=2, sort_keys=True) + "\n")
PY

  rsync "${rsync_flags[@]}" "$dest" "$target:~/.claude/settings.json"
}

log "syncing to $target"
remote_mkdir "~/.config/fish ~/.codex ~/.codex/prompts ~/.claude ~/.claude/commands ~/.claude/skills"

if [[ -d "$HOME/.config/fish" ]]; then
  log "copying fish config"
  if [[ "$dry_run" != "1" ]]; then
    ssh "$target" "rm -f ~/.config/fish/functions/fzf_key_bindings.fish"
  fi
  rsync "${rsync_flags[@]}" --delete \
    --exclude '.git/' \
    --exclude 'fish_variables' \
    --exclude 'fishd.*' \
    --exclude 'functions/brew.fish' \
    --exclude 'functions/brew86.fish' \
    --exclude 'functions/fzf_key_bindings.fish' \
    "$HOME/.config/fish/" "$target:~/.config/fish/"
fi

log "copying Codex prompt files"
rsync_if_exists "$HOME/.codex/AGENTS.md" "$target:~/.codex/AGENTS.md"
if [[ -d "$HOME/.codex/prompts" ]]; then
  rsync "${rsync_flags[@]}" --delete \
    --include '*.md' \
    --exclude '*' \
    "$HOME/.codex/prompts/" "$target:~/.codex/prompts/"
fi
generate_codex_config

log "copying Claude prompt files"
rsync_if_exists "$HOME/.claude/CLAUDE.md" "$target:~/.claude/CLAUDE.md"
if [[ -d "$HOME/.claude/commands" ]]; then
  rsync "${rsync_flags[@]}" --delete \
    --include '*.md' \
    --exclude '*' \
    "$HOME/.claude/commands/" "$target:~/.claude/commands/"
fi
if [[ -d "$HOME/.claude/skills" ]]; then
  rsync "${rsync_flags[@]}" --delete \
    --exclude '.git/' \
    "$HOME/.claude/skills/" "$target:~/.claude/skills/"
fi
generate_claude_settings

log "done"
