---
- name: Install kubectl
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: "0755"

- name: Install flux archive
  ansible.builtin.unarchive:
    src: "https://github.com/fluxcd/flux2/releases/download/v{{ flux_version }}/flux_{{ flux_version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/flux
    mode: "0755"

- name: Install helm archive
  ansible.builtin.unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
    creates: /tmp/linux-amd64/helm

- name: Move helm binary
  ansible.builtin.copy:
    src: /tmp/linux-amd64/helm
    dest: /usr/local/bin/helm
    remote_src: true
    mode: "0755"

- name: Install kustomize archive
  ansible.builtin.unarchive:
    src: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/{{ kustomize_version }}/kustomize_{{ kustomize_version }}_linux_amd64.tar.gz"
    dest: /usr/local/bin
    remote_src: true
    creates: /usr/local/bin/kustomize
    mode: "0755"

- name: Install talosctl
  ansible.builtin.get_url:
    url: "https://github.com/siderolabs/talos/releases/download/{{ talosctl_version }}/talosctl-linux-amd64"
    dest: /usr/local/bin/talosctl
    mode: "0755"
