apiVersion: apps/v1
kind: Deployment
metadata:
  name: froystein-jp
  namespace: froystein-jp-dev
spec:
  template:
    spec:
      containers:
        - name: web
          image: ghcr.io/stianfro/froystein.jp:pr-37-56a8655@sha256:912d187a896a925e7ea0596b1dc0974ee4f79e361dd2741bdd5509aec25cbdd7
          volumeMounts:
            - name: analytics-config
              mountPath: /usr/share/nginx/html/analytics-config.js
              subPath: analytics-config.js
              readOnly: true
      volumes:
        - name: analytics-config
          configMap:
            name: froystein-jp-analytics-config
