apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - database.yaml
  - vaultstaticsecret.yaml
  - deployment.yaml
  - routes.yaml
  - authentik-referencegrant.yaml
  - maintenance.yaml
  - monitoring.yaml
  - networkpolicy.yaml
