apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: umami-app
  namespace: umami
spec:
  vaultAuthRef: vault/default
  mount: secret
  type: kv-v2
  path: umami/app
  refreshAfter: 1h
  destination:
    name: umami-app
    create: true
    transformation:
      excludeRaw: true
      templates:
        app-secret:
          text: '{{ .Secrets.app_secret }}'
