apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.24.0
    helm:
      values: |
        tempo:
          retention: 168h  # 7 days
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          metricsGenerator:
            enabled: true
            remoteWriteUrl: http://prometheus-operated.monitoring.svc.cluster.local:9090/api/v1/write

        persistence:
          enabled: true
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          size: 50Gi

        service:
          type: ClusterIP

        serviceMonitor:
          enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tempo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
