apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: tempo
  namespace: tempo
spec:
  parentRefs:
    - name: eg
      namespace: envoy-gateway-system
  hostnames:
    - tempo.talos.froystein.jp
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: tempo-chart
          port: 3100
