apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: flux-system
spec:
  interval: 10m
  releaseName: blackbox-exporter
  targetNamespace: network-monitor
  install:
    createNamespace: true
  chart:
    spec:
      chart: prometheus-blackbox-exporter
      version: 11.9.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    config:
      modules:
        icmp:
          prober: icmp
          timeout: 5s
          icmp:
            preferred_ip_protocol: ip4
        http_2xx:
          prober: http
          timeout: 10s
          http:
            preferred_ip_protocol: ip4
            valid_http_versions:
              - HTTP/1.1
              - HTTP/2.0
            valid_status_codes: []
            follow_redirects: true
            no_follow_redirects: false
    podSecurityContext:
      runAsNonRoot: false
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      readOnlyRootFilesystem: true
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
        add:
          - NET_RAW
    serviceMonitor:
      enabled: false
  driftDetection:
    mode: enabled
