apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blackbox-exporter-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: prometheus-blackbox-exporter
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 9.1.0
    helm:
      releaseName: blackbox-exporter
      values: |
        config:
          modules:
            icmp:
              prober: icmp
              timeout: 5s
              icmp:
                preferred_ip_protocol: ip4
            http_2xx:
              prober: http
              timeout: 10s
              http:
                preferred_ip_protocol: ip4
                valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
                valid_status_codes: []
                follow_redirects: true
                no_follow_redirects: false

        podSecurityContext:
          runAsNonRoot: false

        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - NET_RAW

        serviceMonitor:
          enabled: false
  destination:
    namespace: network-monitor
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
