apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-backup
  namespace: vault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-backup
  namespace: vault
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["vault-backup-token"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-backup
  namespace: vault
subjects:
  - kind: ServiceAccount
    name: vault-backup
    namespace: vault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-backup
