apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-chart
  namespace: argocd
spec:
  project: default
  source:
    chart: vault
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.0
    helm:
      values: |
        global:
          enabled: true
          tlsDisable: true

        server:
          enabled: true
          image:
            repository: hashicorp/vault
            tag: "1.19.0"

          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 500m

          # HA Mode with Raft
          ha:
            enabled: true
            replicas: 3
            raft:
              enabled: true
              setNodeId: true
              config: |
                ui = true
                disable_mlock = true

                listener "tcp" {
                  tls_disable = 1
                  address = "[::]:8200"
                  cluster_address = "[::]:8201"
                }

                storage "raft" {
                  path = "/vault/data"
                  retry_join {
                    leader_api_addr = "http://vault-0.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-1.vault-internal:8200"
                  }
                  retry_join {
                    leader_api_addr = "http://vault-2.vault-internal:8200"
                  }
                }

                service_registration "kubernetes" {}

          # Audit logging
          auditStorage:
            enabled: true
            size: 10Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce

          # Data storage
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: longhorn
            accessMode: ReadWriteOnce

          # Pod anti-affinity to spread across nodes
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: vault
                      component: server
                  topologyKey: kubernetes.io/hostname

          # Environment variables for unseal keys
          extraSecretEnvironmentVars:
            - envName: VAULT_UNSEAL_KEY_1
              secretName: vault-unseal-keys
              secretKey: VAULT_UNSEAL_KEY_1
            - envName: VAULT_UNSEAL_KEY_2
              secretName: vault-unseal-keys
              secretKey: VAULT_UNSEAL_KEY_2
            - envName: VAULT_UNSEAL_KEY_3
              secretName: vault-unseal-keys
              secretKey: VAULT_UNSEAL_KEY_3

          # PostStart hook for auto-unseal
          postStart:
            - /bin/sh
            - -c
            - |
              sleep 15
              if [ -n "$VAULT_UNSEAL_KEY_1" ]; then
                if vault status 2>&1 | grep -q "Sealed.*true"; then
                  echo "Vault is sealed, attempting unseal..."
                  vault operator unseal "$VAULT_UNSEAL_KEY_1" || true
                  vault operator unseal "$VAULT_UNSEAL_KEY_2" || true
                  vault operator unseal "$VAULT_UNSEAL_KEY_3" || true
                fi
              fi

        # UI configuration
        ui:
          enabled: true
          serviceType: ClusterIP

        # Injector disabled (using VSO instead)
        injector:
          enabled: false

  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
