apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-applicationset-controller
spec:
  template:
    spec:
      containers:
        - name: argocd-applicationset-controller
          env:
            - name: ARGOCD_APPLICATIONSET_CONTROLLER_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: argocd-appset-webhook-secret
                  key: secret
