apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-appset-webhook-secret
spec:
  type: kv-v2
  mount: secret
  path: argocd/webhook-secret
  destination:
    name: argocd-appset-webhook-secret
    create: true
  refreshAfter: 60s
  vaultAuthRef: vault/default
